LEX			= flex
YACC		= bison
LEX_FLAG  	= -Pparse
YACC_FLAG 	= -d -p parse

CXX      	= g++
CFLAGS	 	= -O3 -Iinclude -Wall
CFLAGS_STFU	= -Wno-unused-function -Wno-unneeded-internal-declaration
CSRCS     	= $(wildcard src/*.cpp)
CHDRS     	= $(wildcard include/*.h)

COBJS     	= obj/main.o obj/simulator.o obj/circuit.o obj/utils.o obj/parseLEX.o obj/parseYY.o

.PHONY: create_dirs

all : create_dirs bin/cspice

create_dirs:
	mkdir -p bin obj

src/parseLEX.cpp: src/parser.l src/parseYY.hpp
	@echo "> lexing: $<"
	@$(LEX) $(LEX_FLAG) -o$@ $<

src/parseYY.cpp src/parseYY.hpp: src/parser.y
	@echo "> yaccing: $<"
	@$(YACC) $(YACC_FLAG) -o parseYY.cpp $<
	@mv parseYY.cpp src/parseYY.cpp
	@mv parseYY.hpp src/parseYY.hpp
	@ln -sf src/parseYY.hpp include/parseYY.hpp

# Special rule for parseLEX.o to shut up warnings from autogenerated source
obj/parseLEX.o : src/parseLEX.cpp
	$(CXX) $(CFLAGS) ${CFLAGS_STFU} -c -o $@ $<

obj/parseYY.o : src/parser.cpp

bin/cspice : $(COBJS)
	$(CXX) $(CFLAGS) -o $@ $(COBJS)

obj/%.o : src/%.c
	$(CXX) $(CFLAGS) -c -o $@ $<

obj/%.o : src/%.cpp
	$(CXX) $(CFLAGS) -c -o $@ $<

$(COBJS) : $(CHDRS)

clean:
	-rm -f obj/*.o bin/cspice src/parseYY.cpp src/parseYY.hpp src/parseLEX.cpp
	-rm -rf bin obj

